export const VIDEO_STYLES = [
  "Điện ảnh (cinematic)",
  "Chân thực (Realistic)",
  "Hoạt hình 2D",
  "Hoạt hình 3D",
  "Anime",
  "Manga",
  "Disney/Pixar",
  "Studio Ghibli",
  "Tranh sơn dầu",
  "Màu nước",
  "Digital art",
  "Concept art",
  "Low-poly",
  "Sketch",
  "Line-art",
  "Pop art",
  "Cyberpunk",
  "Sci-fi",
  "Vaporwave",
  "Glitch",
  "Hologram",
  "Surreal/Trừu tượng",
  "GoPro POV",
  "Drone shot",
  "FPV drone",
  "CCTV",
  "iPhone thực tế",
  "Handheld",
  "Slow motion",
  "Hyperlapse",
  "Siêu thực (photorealistic)",
  "Documentary style",
  "Macro shot",
  "CGI",
  "Unreal Engine style",
  "Blender render",
  "VFX mô phỏng",
  "Talking head avatar",
  "AI presenter",
  "Lip-sync",
  "Influencer ảo",
  "Miniature",
  "Diorama",
  "Stop-motion",
  "Dreamlike",
  "Liquid motion",
  "Morphing",
  "Kaleidoscope",
  "Fractal",
];